#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx
sudo sed -i "62i\\\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx start 
