#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
apt-get -y update
apt-get install haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 387281-web-01 18.210.33.185:80 check
   server 387281-web-02 107.22.143.17:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
