#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
#displays bad luck on the 4th loop iteration
#displays good luck on the 8th loop iteration
#displays Best School on the other iterations
counter=1
while [ $counter -le 10 ]
do
if [ $counter == 4 ]; then
echo "bad luck"
elif [ $counter == 8 ]; then
echo "good luck"
else
echo "Best School"
fi
	((counter++))
done
