#!/usr/bin/env bash
Bash script that displays numbers from 1 to 20 and:
display 4 and after that bad luck from china
display 9 and after that bad luck from japan
display 17 and after that bad luck from italy
counter=1
while [ $counter -le 20 ]
do
case $counter in 
	5)
	echo "bad luck from China"
	echo "$counter"
	;;
	10)
	echo "bad luck from Japan"
	echo "$counter"
	;;
	18)
	echo "bad luck from Italy"
	echo "$counter"
	;;
*)
	echo "$counter"
	;;
esac
	((counter++))
done
