#!/usr/bin/env bash
Bash script that displays numbers from 1 to 20 and:
display 4 and after that bad luck from china
display 9 and after that bad luck from japan
display 17 and after that bad luck from italy
counter=1
while [ $counter -le 20 ]
do
echo "$counter"
case $counter in 
	4)
	echo "bad luck from China"
	;;
	9)
	echo "bad luck from Japan"
	;;
	17)
	echo "bad luck from Italy"
	;;
esac
	((counter++))
done
