#!/usr/bin/env bash
#Bash script that gives you information about the school file
var=$(school)
if [ -e $var ]; then
	echo "school file exists"
if [ -s $var ]; then
	echo "school file is not empty"
else	
	echo "school file is empty"
fi
if [ -f $var ]; then
	echo "school is a regular file"
else
	echo ""
fi
else
	echo "school file does not exist"
fi
